/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Data;
import Clases.Users;
import Clases.Product;
import Clases.Utility;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.omg.PortableInterceptor.USER_EXCEPTION;
/**
 *
 * @author jalfonso2
 */
public class frmProducts extends javax.swing.JInternalFrame {

    //Create an object from the class Data
    private Data myData;
    private int actProduct = 0;
    private Boolean newReg = false;
    private DefaultTableModel myTable;

    public void setData(Data myData) {
        this.myData = myData;

    }

    public frmProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldIDProduct = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        txtDesc = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        fldDescription = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        txtprice = new javax.swing.JLabel();
        btnLast = new javax.swing.JButton();
        fldPrice = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        txtIIva = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnErrase = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtIdProduct = new javax.swing.JLabel();
        txtConfPwd1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        cmbIva = new javax.swing.JComboBox<>();
        txtNote = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fldTxtaNote = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Products");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        fldIDProduct.setEnabled(false);

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291512_DoubleChevronLeft.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        txtDesc.setText("Description*");
        txtDesc.setEnabled(false);

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291495_ChevronLeft.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        fldDescription.setEnabled(false);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291484_ChevronRight.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtprice.setText("Price*");
        txtprice.setEnabled(false);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291501_DoubleChevronRight.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        fldPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fldPrice.setEnabled(false);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291729_pen-checkbox.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtIIva.setText("IVA");
        txtIIva.setEnabled(false);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291803_add_cross_new_plus_create.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291785_save.png"))); // NOI18N
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490292060_Cancel.png"))); // NOI18N
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnErrase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291915_bin_cancel_close_cross_delete_empty_exit_garbage_minus_out_recycle_remove_trash.png"))); // NOI18N
        btnErrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErraseActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490292082_magnifier.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtIdProduct.setText("ProductID*");
        txtIdProduct.setEnabled(false);

        txtConfPwd1.setText("*Obligatory field");

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTable);

        cmbIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "16%" }));
        cmbIva.setEnabled(false);
        cmbIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIvaActionPerformed(evt);
            }
        });

        txtNote.setText("Notes");
        txtNote.setEnabled(false);

        fldTxtaNote.setColumns(20);
        fldTxtaNote.setRows(5);
        jScrollPane2.setViewportView(fldTxtaNote);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNote, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdProduct, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fldPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIIva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbIva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fldIDProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtConfPwd1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnErrase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProduct)
                    .addComponent(fldIDProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesc)
                    .addComponent(fldDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldPrice)
                    .addComponent(txtprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtIIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cmbIva)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNote)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(txtConfPwd1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //If press the button all the options will be disable except save and cancel (this is only design to handling).
        btnLast.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(false);
        btnFirst.setEnabled(false);
        btnEdit.setEnabled(false);
        btnNew.setEnabled(false);
        btnErrase.setEnabled(false);
        btnNew.setEnabled(false);
        btnSearch.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);

        //Set enable the fields to create a new user
        fldIDProduct.setEnabled(true);
        fldPrice.setEnabled(true);
        fldDescription.setEnabled(true);
        cmbIva.setEnabled(true);
        //Set in blank the fields to create a new user
        fldIDProduct.setText("");
        fldPrice.setText("");
        fldDescription.setText("");
        cmbIva.setSelectedIndex(0);
        //Set focus in the first field when the textfields be enable
        fldIDProduct.requestFocus();

        //Set the boolean val in true
        newReg = true;


    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //If press the button all the options will be disable except save and cancel (this is only design to handling).
        btnLast.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(false);
        btnFirst.setEnabled(false);
        btnEdit.setEnabled(false);
        btnNew.setEnabled(false);
        btnErrase.setEnabled(false);
        btnNew.setEnabled(false);
        btnSearch.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);

        //Set enable the fields to edit a new user
        fldIDProduct.setEnabled(true);
        fldPrice.setEnabled(true);
        fldDescription.setEnabled(true);
        cmbIva.setEnabled(true);

        //Set focus in the first field when the textfields be enable
        fldDescription.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //If press this button the options will be stay normal ((this is only design to handling)).
        btnLast.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnFirst.setEnabled(true);
        btnEdit.setEnabled(true);
        btnNew.setEnabled(true);
        btnErrase.setEnabled(true);
        btnNew.setEnabled(true);
        btnSearch.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);

        //Set disabled when return to view the users
        fldIDProduct.setEnabled(false);
        fldPrice.setEnabled(false);
        fldDescription.setEnabled(false);
        cmbIva.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        //Create a position of the user
        int pos = myData.productPosition(fldIDProduct.getText());

        //Create a mesage if the user dont ingress any character in 
        if (fldIDProduct.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please write an productId ");
            fldIDProduct.requestFocus();
            return;
        }

        if (fldDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please write a description of product.");
            fldDescription.requestFocus();
            return;
        }

        if (Utility.isNumeric(fldPrice.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Please write a price val");
            fldPrice.requestFocus();
            return;
        }
        
        int price = Integer.parseInt(fldPrice.getText());
        
        if (price <= 0) {
            JOptionPane.showMessageDialog(rootPane, "The value need be mayor to zero");
            fldPrice.requestFocus();
            return;
        }
        
        //If the product is new validate the user exist
        if (newReg) {
            if (pos != -1) {
                JOptionPane.showMessageDialog(rootPane, "The product exist now in the data base");
                fldIDProduct.requestFocus();
                return;
            }
        } else {
            if (pos == -1) {
                JOptionPane.showMessageDialog(rootPane, "The product not exist");
                fldIDProduct.requestFocus();
                return;
            }
        }

        //Create the user in the object
        Product myProduct = new Product(
                fldIDProduct.getText(),
                fldDescription.getText(),
                price,
                cmbIva.getSelectedIndex());
        String message;

        if (newReg) {
            message = myData.addProduct(myProduct);
        } else {
            message = myData.modProduct(myProduct, pos);
        }

        JOptionPane.showMessageDialog(rootPane, message);

        //If press this button the options will be stay normal (this is only design to handling).
        btnLast.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnFirst.setEnabled(true);
        btnEdit.setEnabled(true);
        btnNew.setEnabled(true);
        btnErrase.setEnabled(true);
        btnNew.setEnabled(true);
        btnSearch.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);

        //Set disabled when return to view the users
        fldIDProduct.setEnabled(false);
        fldDescription.setEnabled(false);        
        fldPrice.setEnabled(false);
        cmbIva.setEnabled(false);
        //Set the boolean val in false
        newReg = false;

        //Act the info of the Table
        infoTable();
    }//GEN-LAST:event_btnSaveActionPerformed


    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        showReg();
        infoTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        actProduct = 0;
        showReg();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        actProduct++;
        if (actProduct == myData.numProducts()) {
            actProduct = 0;
        }
        showReg();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        actProduct--;
        if (actProduct == -1) {
            actProduct = myData.numProducts()- 1;
        }
        showReg();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        actProduct = myData.numProducts()- 1;
        showReg();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnErraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErraseActionPerformed
        int response = JOptionPane.showConfirmDialog(rootPane, "Are you secure to delete the regist?");
        if (response != 0) {
            return;
        }
        String msg;
        msg = myData.deleteProduct(actProduct);
        JOptionPane.showMessageDialog(rootPane, msg);
        actProduct = 0;
        showReg();

        //Act the info of the Table
        infoTable();
    }//GEN-LAST:event_btnErraseActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String product = JOptionPane.showInputDialog("Insert product ID");
        if (product.equals("")) {
            return;
        }
        int pos = myData.productPosition(product);
        if (pos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Product not exist");
            return;
        }
        actProduct = pos;
        showReg();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIvaActionPerformed
        
    }//GEN-LAST:event_cmbIvaActionPerformed

    private void showReg() {

        fldIDProduct.setText(myData.getProducts()[actProduct].getIdProduct());
        fldDescription.setText(myData.getProducts()[actProduct].getProductDescription());
        fldPrice.setText("" + myData.getProducts()[actProduct].getProductPrice());
        fldTxtaNote.setText(myData.getProducts()[actProduct].getNote());
        cmbIva.setSelectedIndex(myData.getProducts()[actProduct].getIva());

    }
  
    private void infoTable() {
        String titles[] = {"ID Product", "Description", "Price", "Iva", "Notes"};
        String reg[] = new String[5];
        myTable = new DefaultTableModel(null, titles);
        for (int i = 0; i < myData.numProducts(); i++) {
            reg[0] = myData.getProducts()[i].getIdProduct();
            reg[1] = myData.getProducts()[i].getProductDescription();
            reg[2] = "" + myData.getProducts()[i].getProductPrice();
            reg[3] = profile(myData.getProducts()[i].getIva());
            reg[4] = myData.getProducts()[i].getNote();
            myTable.addRow(reg);
        }
        tblTable.setModel(myTable);
    }

 
    private String profile(int idIva)
    {
        switch(idIva){
            case 0: return "0%";
            case 1: return "10%";
            case 2: return "16%";
            default: return "Not Iva";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnErrase;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbIva;
    private javax.swing.JTextField fldDescription;
    private javax.swing.JTextField fldIDProduct;
    private javax.swing.JTextField fldPrice;
    private javax.swing.JTextArea fldTxtaNote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTable;
    private javax.swing.JLabel txtConfPwd1;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JLabel txtIIva;
    private javax.swing.JLabel txtIdProduct;
    private javax.swing.JLabel txtNote;
    private javax.swing.JLabel txtprice;
    // End of variables declaration//GEN-END:variables
}
