/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Data;

/**
 *
 * @author jalfonso2
 */
public class frmusersinternal extends javax.swing.JInternalFrame {

  
       
      //Create an object from the class Data
    private Data myData;
     private int actUser = 0; 
    
    public void setData (Data myData){
        this.myData = myData;
       
    }
    
    
    
    public frmusersinternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldID = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        fldName = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        txtLstName = new javax.swing.JLabel();
        btnLast = new javax.swing.JButton();
        fldLastName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        txtPwd = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cmbxProf = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        txtProf = new javax.swing.JLabel();
        btnErrase = new javax.swing.JButton();
        txtConfPwd = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtId = new javax.swing.JLabel();
        fldPwd = new javax.swing.JPasswordField();
        fldConfPwd = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        fldID.setEnabled(false);

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291512_DoubleChevronLeft.png"))); // NOI18N

        txtName.setText("Name");
        txtName.setEnabled(false);

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291495_ChevronLeft.png"))); // NOI18N

        fldName.setEnabled(false);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291484_ChevronRight.png"))); // NOI18N

        txtLstName.setText("Last name");
        txtLstName.setEnabled(false);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291501_DoubleChevronRight.png"))); // NOI18N

        fldLastName.setEnabled(false);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291729_pen-checkbox.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtPwd.setText("Password");
        txtPwd.setEnabled(false);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291803_add_cross_new_plus_create.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291785_save.png"))); // NOI18N
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbxProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the profile", "Admin", "User" }));
        cmbxProf.setEnabled(false);
        cmbxProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxProfActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490292060_Cancel.png"))); // NOI18N
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtProf.setText("Profile");
        txtProf.setEnabled(false);

        btnErrase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490291915_bin_cancel_close_cross_delete_empty_exit_garbage_minus_out_recycle_remove_trash.png"))); // NOI18N

        txtConfPwd.setText("Confirm Password");
        txtConfPwd.setEnabled(false);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1490292082_magnifier.png"))); // NOI18N

        txtId.setText("UserID");
        txtId.setEnabled(false);

        fldPwd.setEnabled(false);

        fldConfPwd.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnErrase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtConfPwd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPwd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fldConfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fldID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbxProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId)
                    .addComponent(fldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLstName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPwd)
                            .addComponent(fldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConfPwd)
                            .addComponent(fldConfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnErrase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxProfActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        //If press the button all the options will be disable except save and cancel (this is only design to handling).
        btnLast.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(false);
        btnFirst.setEnabled(false);
        btnEdit.setEnabled(false);
        btnNew.setEnabled(false);
        btnErrase.setEnabled(false);
        btnNew.setEnabled(false);
        btnSearch.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);
        
        //Set enable the fields to create a new user
          fldID.setEnabled(true);
          fldConfPwd.setEnabled(true);
          fldLastName.setEnabled(true);
          fldName.setEnabled(true);
          fldPwd.setEnabled(true);
          cmbxProf.setEnabled(true);
        //Set in blank the fields to create a new user
          fldID.setText("");
          fldConfPwd.setText("");
          fldLastName.setText("");
          fldName.setText("");
          fldPwd.setText("");
          cmbxProf.setSelectedIndex(0);
          //Set focus in the first field when the textfields be enable
          fldID.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //If press the button all the options will be disable except save and cancel (this is only design to handling).
        btnLast.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(false);
        btnFirst.setEnabled(false);
        btnEdit.setEnabled(false);
        btnNew.setEnabled(false);
        btnErrase.setEnabled(false);
        btnNew.setEnabled(false);
        btnSearch.setEnabled(false);
        btnSave.setEnabled(true);
        btnCancel.setEnabled(true);
        
        //Set enable the fields to edit a new user
          fldConfPwd.setEnabled(true);
          fldLastName.setEnabled(true);
          fldName.setEnabled(true);
          fldPwd.setEnabled(true);
          cmbxProf.setEnabled(true);
        
        //Set focus in the first field when the textfields be enable
           fldName.requestFocus();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //If press this button the options will be stay normal ((this is only design to handling)).
        btnLast.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnFirst.setEnabled(true);
        btnEdit.setEnabled(true);
        btnNew.setEnabled(true);
        btnErrase.setEnabled(true);
        btnNew.setEnabled(true);
        btnSearch.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
        
        //Set disabled when return to view the users
          fldID.setEnabled(false);
          fldConfPwd.setEnabled(false);
          fldLastName.setEnabled(false);
          fldName.setEnabled(false);
          fldPwd.setEnabled(false);
          cmbxProf.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //If press this button the options will be stay normal (this is only design to handling).
        btnLast.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnFirst.setEnabled(true);
        btnEdit.setEnabled(true);
        btnNew.setEnabled(true);
        btnErrase.setEnabled(true);
        btnNew.setEnabled(true);
        btnSearch.setEnabled(true);
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
        
          //Set disabled when return to view the users
          fldID.setEnabled(false);
          fldConfPwd.setEnabled(false);
          fldLastName.setEnabled(false);
          fldName.setEnabled(false);
          fldPwd.setEnabled(false);
          cmbxProf.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
        fldID.setText(myData.getUsers()[actUser].getIdUser());
        fldName.setText(myData.getUsers()[actUser].getName());
        fldLastName.setText(myData.getUsers()[actUser].getLastName());
        fldPwd.setText(myData.getUsers()[actUser].getPassword());
        fldConfPwd.setText(myData.getUsers()[actUser].getPassword());
        cmbxProf.setSelectedIndex(myData.getUsers()[actUser].getProfile());
        
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnErrase;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbxProf;
    private javax.swing.JPasswordField fldConfPwd;
    private javax.swing.JTextField fldID;
    private javax.swing.JTextField fldLastName;
    private javax.swing.JTextField fldName;
    private javax.swing.JPasswordField fldPwd;
    private javax.swing.JLabel txtConfPwd;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtLstName;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtProf;
    private javax.swing.JLabel txtPwd;
    // End of variables declaration//GEN-END:variables
}
